### PR TITLE
Fixed checking of core.edit.own in views and in models of contenthistory, and also added category form case

### PR DESCRIPTION
**Pull request by ggppdk**

### CODE REVIEW

**Comment by infograf768** [comment]
@ggppdk
I have an issue with your patch.
If an item (tested with article) has been modified for example by a Super User, thus adding a new version, then the user who created the article can edit it but can't access anymore to the Versions and gets a 500. It worked ok before with my PR.

Here is a list of articles: New article has been created by user jms (with only edit-own permission). It is editable.
screen shot 2016-06-21 at 10 36 25

The Versions button does exist and is clickable:
screen shot 2016-06-21 at 10 37 25

Clicking on it gives:
screen shot 2016-06-21 at 10 38 11

**Comment by infograf768** [comment]
I guess it maybe because of
`$result = in_array((int) $record->ucm_item_id, $values);`
instead of
`$result = in_array((int) $record->ucm_item_id, $typeEditables);`

If I do that in the 3 models, I get at least the first modal with the list OK and can Restore one version made by jms, but can't preview or compare anything.

**Comment by infograf768** [comment]
So, basically, if I do not apply the part of your changes to the contenthistory models, all looks like working OK

**Comment by ggppdk** [comment]
I had to redo the patch twice, i overwrote it once while trying to use a pull-request from command line, eventually i commited to my own branch and made pull request from GitHub UI,

yes this 

```
$result = in_array((int) $record->ucm_item_id, $values);
```

should 

```
$result = in_array((int) $record->ucm_item_id, $typeEditables);
```

i re-test and update

**Comment by infograf768** [comment]
Please test Compare and Preview too as these do not work, even when that line is changed.
TBH, I do not understand why you modify these way the models while it works well in my PR.

**Comment by ggppdk** [comment]
> I do not understand why you modify these way the models while it works well in my PR.

Your PR code works, but it has an important oversight, it only checks if user has "core.edit.own" on current item **but it does not check if user is owner !! of the record**
- effectively all your original code used "core.edit.own" as "core.edit"

thus if user has core.edit.own on article's category (but does not have core.edit),
then user can use versioning stuff without limitations on ALL articles of the category regardless of being owner or not (i don't mean open edit form, i mean call versioning code via URL)

about the check in my PR, i ll test and fix

**Comment by ggppdk** [comment]
I have fixed the checks in the models

**Comment by infograf768** [comment]
Understand. Will test later for Compare and Review

**Comment by infograf768** [comment]
Works now. :)

**Pull request merged**
