### PR TITLE
[4.0] Batch copy workflow association, too

### PR DESCRIPTION
**Pull request by richard67**
PR for [https://github.com/joomla/joomla-cms/pull/26835](https://github.com/joomla/joomla-cms/pull/26835).

Just have tested here, seems to work.

If you want, merge this and change the scope of your PR to handle the general batch copy problem, too.

### CODE REVIEW

**Comment by infograf768** [comment]
not at desktop right now, will look later.

**Comment by richard67** [comment]
Hmm, there seems to be a PR already doing it, #24519 . Is RTC but seems to be more complicated than my way. But maybe it's the more correct way? Anyway. Is RTC => someone merge.

**Comment by richard67** [comment]
Closing because there is PR [https://github.com/joomla/joomla-cms/pull/24519](https://github.com/joomla/joomla-cms/pull/24519) already solving that.

**Comment by alikon** [comment]
why closing this with only 3 line of code using API, instead of #24519 which is not using API ?

**Comment by richard67** [comment]
Reopened. But I am not sure if what I do here is correct. Haven't checked the other PR in details but maybe the other starts workflow for copied articles from beginning, while my patch just copies the workflow association with the same workflow state as the copy source.

@wilsonge As soon as you find time, could you check what is right, this here or [https://github.com/joomla/joomla-cms/pull/24519](https://github.com/joomla/joomla-cms/pull/24519)?

**Comment by richard67** [comment]
I've just checked what [https://github.com/joomla/joomla-cms/pull/24519](https://github.com/joomla/joomla-cms/pull/24519) does, and left a comment there: [https://github.com/joomla/joomla-cms/pull/24519#issuecomment-547329485](https://github.com/joomla/joomla-cms/pull/24519#issuecomment-547329485).

@alikon @infograf768 Please check and comment there.

I don't want to discourage some new contributor by replacing his PR, so I thought I should give him a chance to change that himself.

**Comment by infograf768** [comment]
@richard67 
The more I think of it, the more confused I get.

We have 2 cases:

1. we copy to the same category.
In that case keeping the existing workflow is fine.

2. We copy to another category
Should'nt the workflow be the one used for that category?

**Comment by richard67** [comment]
Yes, maybe that’ the reason why that other PR is so complicated? I have to check tonight after work, German time.

**Comment by richard67** [comment]
@infograf768 I've just checked: It seems that other PR makes a few checks and resets some flags like e.g. published, but the workflow association is handled in the same way as I do, i.e. just copy with same workflow ID as the old article has. But I am not sure if I understand all right. Let's see if someone answers my comment there.

**Comment by wilsonge** [comment]
IF your PR works it looks far more sensible to me

**Comment by richard67** [comment]
@wilsonge It works, and as far as I can see most of the code added PR [https://github.com/joomla/joomla-cms/pull/24519](https://github.com/joomla/joomla-cms/pull/24519) is identical with the code in the base class, only insert of a new workflow association is added to that, and so it seems to do the same as my PR here does. But there was so much review done on that PR by people of who I think that they have much more knowledge on that than I have ... why hasn't someone found the easier solution before me? This is what makes me worry that I might be missing something. And I don't want to discourage a new contributor by throwing away his PR.

**Comment by wilsonge** [comment]
OK in which case this is definitely the fix

**Comment by infograf768** [comment]
tks

**Comment by richard67** [comment]
Thanks too.

**Pull request merged**
