### PR TITLE
[4.0] Use featured up and down times from copied article, if set

### PR DESCRIPTION
**Pull request by richard67**
PR for [https://github.com/joomla/joomla-cms/pull/26835](https://github.com/joomla/joomla-cms/pull/26835).

Just have tested here, seems to work.

### CODE REVIEW

**Comment by infograf768** [comment]
I am confused...
`$table` can't at the same time represent `_content` with the `featured` column and `_content_frontpage` with both `featured_up` and `featured_down` columns.

It looks like the query should fetch `publish_up` and `publish_down`

**Comment by richard67** [comment]
@infograf768 Table contains those columns because it has them copied in the Content.php table class. I know, it is strange.

**Comment by richard67** [comment]
Maybe @SharkyKZ could check if it should be done in a different way?

**Comment by richard67** [comment]
Here is the strange function which does it:

[https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/Content.php#L387](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/Content.php#L387).

**Comment by infograf768** [comment]
:grimacing:

**Comment by richard67** [comment]
Agree, is all ... let me say friendly ... not optimal with the featured up and down ... at the beginning it looked like it could be a nulldate problem so I became involved ... and now I wish I was in holiday somewhere where is no internet.

**Comment by SharkyKZ** [comment]
As I said before, I'm not sure whether we should be loading properties from foreign tables into table object like this. To me this looks wrong. Maybe a maintainer should take a look at this and decide.

**Comment by richard67** [comment]
@SharkyKZ To me it also looks wrong, fully agree with you, but when I tried to fix it here I failed, so I thoight there was something which I missed or did not unserstand, and so i gave it up and started to fix what I could see in PHP logs.

**Comment by richard67** [comment]
And so this thing is a bit like a pain in ...ss.

**Comment by richard67** [comment]
@SharkyKZ I think I slowly develop an idea how the featured up and down should be done in the right way. Not sure if I can already provide a fix today, but tomorrow and Tuesday I have time, too. Let me know if you want to do the same and will be faster. I'll have a break right now for a few hours.

**Comment by SharkyKZ** [comment]
You can do it if you want.

**Comment by infograf768** [comment]
Merged for now to go on solving batch copy.

**Comment by richard67** [comment]
@SharkyKZ For now it works here, but I agree with you, the featured up and down times have to be handled in another way, models have to do that, collect data from different tables, not the content table class has to copy columns from other tables. This should be fixed with a future PR.

**Pull request merged**
